#!/bin/sh
set -eu
ROOT=$(CDPATH= cd "$(dirname "$0")/.." && pwd)
DEST="$ROOT/dist/install-ollama-agent-config.sh"
mkdir -p "$ROOT/dist"

{
  printf '%s\n' '#!/bin/sh'
  printf '%s\n' '# Generated by scripts/make-dist.sh — do not edit.'
  printf '%s\n' 'set -eu'
  printf '%s\n' '( set -o pipefail ) 2>/dev/null && set -o pipefail'
  printf '%s\n' 'CBA_DIST=1'
  printf '%s\n' 'CBA_ROOT='
  printf '\n'

  # Embed Python helpers
  printf '%s\n' '_CBA_PYDIR='
  printf '%s\n' '_cba_extract_py() {'
  printf '%s\n' '  _n=$1'
  printf '%s\n' '  if [ -z "${_CBA_PYDIR:-}" ]; then'
  printf '%s\n' '    _CBA_PYDIR=${TMPDIR:-/tmp}/cba-py.$$'
  printf '%s\n' '    mkdir -p "$_CBA_PYDIR"'
  printf '%s\n' '    chmod 700 "$_CBA_PYDIR"'
  for py in catalog.py json_util.py toml_upsert.py fetch.py; do
    printf '%s\n' "    cat > \"\$_CBA_PYDIR/$py\" <<'CBA_PY_${py}'"
    cat "$ROOT/lib/$py"
    printf '%s\n' "CBA_PY_${py}"
    printf '%s\n' "    chmod 700 \"\$_CBA_PYDIR/$py\""
  done
  printf '%s\n' '  fi'
  printf '%s\n' '  printf "%s\n" "$_CBA_PYDIR/$_n"'
  printf '%s\n' '}'
  printf '\n'

  for f in \
    "$ROOT/lib/00-posix.sh" \
    "$ROOT/lib/10-linuxulator.sh" \
    "$ROOT/lib/20-discover.sh" \
    "$ROOT/lib/30-classify.sh" \
    "$ROOT/lib/40-backup.sh" \
    "$ROOT/lib/50-validate.sh" \
    "$ROOT/adapters/claude.sh" \
    "$ROOT/adapters/junie.sh" \
    "$ROOT/adapters/grok.sh"
  do
    printf '%s\n' "# --- BEGIN $(basename "$f") ---"
    cat "$f"
    printf '%s\n' "# --- END $(basename "$f") ---"
    printf '\n'
  done

  # install.sh body without the repo-only bootstrap/source block
  awk '
    BEGIN {skip=0}
    /^# --- CBA_REPO_BEGIN ---/ {skip=1; next}
    /^# --- CBA_REPO_END ---/ {skip=0; next}
    skip {next}
    /^#!\/bin\/sh/ {next}
    /^# ollama-agent-config/ {next}
    /^set -eu/ {next}
    /^\( set -o pipefail/ {next}
    {print}
  ' "$ROOT/install.sh"
} > "$DEST"

chmod 755 "$DEST"
( cd "$ROOT/dist" && sha256sum install-ollama-agent-config.sh > install-ollama-agent-config.sh.sha256 )
sh "$ROOT/scripts/secret-scan.sh" "$DEST"
echo "wrote $DEST"
